version: '3.7'
services:

  rabbitsave-write-to-queue:
    build: .
    container_name: rabbitsave-write-to-queue
    environment:
      - RABBITMQ_HOST=rabbit-2
      - RABBITMQ_PORT=5672
      - RABBITMQ_QUEUE_COUNT=1
      - INPUT_FILE=fo_random.txt
    networks:
      - rabbitsave-network        

networks:
  rabbitsave-network:
    name: rabbitsave-network      

