version: '3.7'
services:

  rabbit-1:
    image: rabbitmq
    container_name: rabbit-1
    hostname: rabbit-1
    volumes:
      - "./rabbit_clusters/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50001:5672      


  rabbit-2:
    image: rabbitmq
    container_name: rabbit-2
    hostname: rabbit-2
    volumes:
      - "./rabbit_clusters/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50002:5672     


  rabbit-3:
    image: rabbitmq
    container_name: rabbit-3
    hostname: rabbit-3
    volumes:
      - "./rabbit_clusters/.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50003:5672                 


  rabbit-cluster-2:
    build: rabbit_clusters/.
    container_name: rabbit-cluster-2
    environment:
      CLUSTER_NODENAME: rabbit@rabbit-1
      RABBITMQ_NODENAME: rabbit@rabbit-2     
      WAIT_FOR_RABBIT: 30 
    depends_on:
      - rabbit-1
      - rabbit-2
      - rabbit-3

  rabbit-cluster-3:
    build: rabbit_clusters/.
    container_name: rabbit-cluster-3
    environment:
      CLUSTER_NODENAME: rabbit@rabbit-1
      RABBITMQ_NODENAME: rabbit@rabbit-3
      WAIT_FOR_RABBIT: 30
    depends_on:    
      - rabbit-cluster-2

