version: '3.7'
services:

  rabbit-1:
    image: rabbitmq
    container_name: rabbit-1
    hostname: rabbit-1
    volumes:
      - "./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50001:5672      

  rabbit-2:
    image: rabbitmq
    container_name: rabbit-2
    hostname: rabbit-2
    volumes:
      - "./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50002:5672     

  rabbit-3:
    image: rabbitmq
    container_name: rabbit-3
    hostname: rabbit-3
    volumes:
      - "./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50003:5672       
      
  postgres:
    image: "postgres"
    container_name: postgres-rabbitsave
    environment:
      - POSTGRES_PASSWORD=sortsavepass
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - "5432:5432"      
