version: '3.7'
services:

  rabbit-1:
    image: rabbitmq
    container_name: rabbit-1
    hostname: rabbit-1
    volumes:
      - "./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50001:5672      
    networks:
      - rabbitsave-network        

  rabbit-2:
    image: rabbitmq
    container_name: rabbit-2
    hostname: rabbit-2
    volumes:
      - "./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50002:5672     
    networks:
      - rabbitsave-network        

  rabbit-3:
    image: rabbitmq
    container_name: rabbit-3
    hostname: rabbit-3
    volumes:
      - "./.erlang.cookie:/var/lib/rabbitmq/.erlang.cookie"
    ports:
      - 50003:5672     
    networks:
      - rabbitsave-network        
      
  postgres:
    image: "postgres"
    container_name: postgres-rabbitsave
    environment:
      - POSTGRES_PASSWORD=rabbitsavepass
    volumes:
      - "./init.sql:/docker-entrypoint-initdb.d/init.sql"
    ports:
      - 5432:5432
    networks:
      - rabbitsave-network         

networks:
  rabbitsave-network:
    name: rabbitsave-network
