version: '3.7'
services:

  mongos-1:
    image: mongo
    container_name: mongos-1
    hostname: mongos-1
    volumes:
      - ./mongos.config:/etc/mongo/mongos.config
      - ./init.js:/usr/local/mongos-init/init.js
    entrypoint: mongos
    command: --config /etc/mongo/mongos.config
    networks:
      - rabbitsave-network           
    ports:
      - 60001:27017

  mongos-2:
    image: mongo
    container_name: mongos-2
    hostname: mongos-2
    volumes:
      - ./mongos.config:/etc/mongo/mongos.config
    entrypoint: mongos
    command: --config /etc/mongo/mongos.config
    networks:
      - rabbitsave-network           
    ports:
      - 60002:27017      


networks:
  rabbitsave-network:
    name: rabbitsave-network
